services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - psql_network:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - my_network
  user_app:
    image: user__app
    build:
      context: .
    container_name: user_app
    env_file:
      - .env
    command: /user_api/script/run.sh
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    networks:
      - my_network

volumes:
  psql_network:
    name: psql_network

networks:
  my_network:
    name: my_network